plugins {
    id 'com.android.application' version '8.7.3'
}

android {
    namespace 'se.caanel.field'
    compileSdk 35

    defaultConfig {
        applicationId "se.caanel.field"
        minSdk 26
        targetSdk 35
        versionCode 77
        versionName "9.3.0-build77"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    implementation 'androidx.webkit:webkit:1.12.1'
    implementation 'androidx.core:core:1.15.0'
    implementation 'com.google.ar:core:1.45.0'
}
